### ISSUE TITLE
Add all images here

### ISSUE THREAD

**Issue by madhavtummala** [arnejasaksham/InterIITTechMeet#3]

**Comment by madhavtummala** [comment]
![Screenshot 2019-12-21 at 7 09 11 PM](https://user-images.githubusercontent.com/29799995/71308812-09811380-2427-11ea-956c-9247f61f2328.png)
![Screenshot 2019-12-21 at 7 09 06 PM](https://user-images.githubusercontent.com/29799995/71308813-0be36d80-2427-11ea-98c9-90dcc7e04fda.png)
![Screenshot 2019-12-21 at 7 08 44 PM](https://user-images.githubusercontent.com/29799995/71308815-0ede5e00-2427-11ea-9040-1e08641cae9a.png)
![Screenshot 2019-12-21 at 7 08 09 PM](https://user-images.githubusercontent.com/29799995/71308816-11d94e80-2427-11ea-9fb9-eddab65a861e.png)
![Screenshot 2019-12-21 at 5 46 20 PM](https://user-images.githubusercontent.com/29799995/71308822-1f8ed400-2427-11ea-9ab0-c7b68f68b8d9.png)
![Screenshot 2019-12-21 at 7 22 00 PM](https://user-images.githubusercontent.com/29799995/71308832-2cabc300-2427-11ea-9bad-8ba0f05843a8.png)

**Comment by madhavtummala** [comment]
![Screenshot_20191221-190505](https://user-images.githubusercontent.com/29799995/71308919-f458b480-2427-11ea-8f48-40e16c531371.jpg)
![Screenshot_20191221-190509](https://user-images.githubusercontent.com/29799995/71308920-f589e180-2427-11ea-919c-7fad908ffc0c.jpg)
![Screenshot_20191221-190513](https://user-images.githubusercontent.com/29799995/71308918-f15dc400-2427-11ea-943f-ae754fd93522.jpg)
![Screenshot_20191221-190704](https://user-images.githubusercontent.com/29799995/71308915-e30fa800-2427-11ea-80bc-112a4463c7aa.jpg)
![Screenshot_20191221-190709](https://user-images.githubusercontent.com/29799995/71308916-e5720200-2427-11ea-8463-51057cf277c4.jpg)
![Screenshot_20191221-191507](https://user-images.githubusercontent.com/29799995/71308922-f884d200-2427-11ea-854d-10c34b282b89.jpg)
![Screenshot_20191221-191714](https://user-images.githubusercontent.com/29799995/71308924-fae72c00-2427-11ea-90fc-c2a56078e34f.jpg)
![Screenshot_20191221-192100](https://user-images.githubusercontent.com/29799995/71308925-fcb0ef80-2427-11ea-86df-f0695f6a4293.jpg)

**Comment by apsknight** [comment]
<img width="608" alt="Screenshot 2019-12-21 at 19 56 16" src="https://user-images.githubusercontent.com/19551774/71309278-1d7b4400-242c-11ea-8fdb-9b8e6819a4cc.png">

**Comment by madhavtummala** [comment]
![Screenshot 2019-12-21 at 8 24 21 PM](https://user-images.githubusercontent.com/29799995/71309606-ec047780-242f-11ea-858e-a34e14d44a92.png)

**Comment by madhavtummala** [comment]
![Screenshot 2019-12-21 at 8 28 13 PM](https://user-images.githubusercontent.com/29799995/71309644-78af3580-2430-11ea-8013-18a17390ce71.png)

**Comment by madhavtummala** [comment]
![signage](https://user-images.githubusercontent.com/29799995/71309714-4baf5280-2431-11ea-96c0-00a3df8e884c.png)

**Comment by madhavtummala** [comment]
![Screenshot_20191221-192100](https://user-images.githubusercontent.com/29799995/71309955-2a9c3100-2434-11ea-9eed-1bde40643d23.jpg)

**Comment by apsknight** [comment]
<img width="580" alt="Screenshot 2019-12-21 at 20 54 58" src="https://user-images.githubusercontent.com/19551774/71309960-38ea4d00-2434-11ea-98be-50038c12fe34.png">

**Comment by madhavtummala** [comment]
<img width="580" alt="71309960-38ea4d00-2434-11ea-98be-50038c12fe34" src="https://user-images.githubusercontent.com/29799995/71309992-86ff5080-2434-11ea-85af-489890e927e8.png">

**Comment by apsknight** [comment]
<img width="596" alt="Screenshot 2019-12-21 at 20 45 09" src="https://user-images.githubusercontent.com/19551774/71310008-c62da180-2434-11ea-9404-6b709ee932e1.png">

**Comment by madhavtummala** [comment]
![Screenshot_20191221-192100-2](https://user-images.githubusercontent.com/29799995/71310019-fe34e480-2434-11ea-920d-4018672a3187.jpg)
